// <auto-generated />
using System;
using FlightManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightManagerApi.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightManagerApi.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAirReady")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightManagerApi.Models.Leg", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("CurrentLeg")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChangeStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("Next")
                        .HasColumnType("int");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Legs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLeg = 1,
                            IsChangeStatus = false,
                            Next = 2,
                            Number = 1,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentLeg = 2,
                            IsChangeStatus = false,
                            Next = 4,
                            Number = 2,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 3,
                            CurrentLeg = 4,
                            IsChangeStatus = false,
                            Next = 8,
                            Number = 3,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 4,
                            CurrentLeg = 8,
                            IsChangeStatus = false,
                            Next = 272,
                            Number = 4,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 5,
                            CurrentLeg = 16,
                            IsChangeStatus = false,
                            Next = 96,
                            Number = 5,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 6,
                            CurrentLeg = 32,
                            IsChangeStatus = false,
                            Next = 128,
                            Number = 6,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 7,
                            CurrentLeg = 64,
                            IsChangeStatus = false,
                            Next = 128,
                            Number = 7,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 8,
                            CurrentLeg = 128,
                            IsChangeStatus = false,
                            Next = 8,
                            Number = 8,
                            WaitTime = 3
                        });
                });

            modelBuilder.Entity("FlightManagerApi.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("LegId");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("FlightManagerApi.Models.Leg", b =>
                {
                    b.HasOne("FlightManagerApi.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightManagerApi.Models.Logger", b =>
                {
                    b.HasOne("FlightManagerApi.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightManagerApi.Models.Leg", "Leg")
                        .WithMany()
                        .HasForeignKey("LegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Leg");
                });
#pragma warning restore 612, 618
        }
    }
}
